- hosts: localhost
  gather_facts: no
  become: no
  #force_handlers: yes
  tasks:
  - name: first task that notifies handler-a
    command: date
    notify: handler-a
  - name: second task that always fails
    fail:
      msg: FAILURE IN THE SECOND TASK
  handlers:
  - name: handler-a
    debug:
      msg: I am handler-a. Who called me?
